# Default values for devops-platform.
backend:
  replicaCount: 4
  image:
    repository: khalilsmida/devops-backend
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080

frontend:
  replicaCount: 2
  image:
    repository: khalilsmida/devops-frontend
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: devops-app.local
      paths:
        - path: /api
          pathType: Prefix
          serviceName: backend
        - path: /
          pathType: Prefix
          serviceName: frontend

# Tag for forcing redeployments
revision: "f10daea3bd610f363089e8c56173cdff143a7080"

database:
  enabled: true
  image: postgres:15
  user: admin
  password: devops_password
  db: devops_db
  port: 5432
  storageSize: 1Gi
