# Default values for devops-platform.
backend:
  replicaCount: 2
  image:
    repository: khalilsmida/devops-backend
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080

frontend:
  replicaCount: 2
  image:
    repository: khalilsmida/devops-frontend
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: devops-app.local
      paths:
        - path: /api
          pathType: Prefix
          serviceName: backend
        - path: /
          pathType: Prefix
          serviceName: frontend
<<<<<<< HEAD

# Tag for forcing redeployments (Updated to latest)
revision: "0d49183f8dbf71fb1733a95a9684b43e153155d7"
=======
# Tag for forcing redeployments
<<<<<<< HEAD
revision: "0d49183f8dbf71fb1733a95a9684b43e153155d7"
>>>>>>> d07cd8f1f649a3cc78d2bbe71238ce955a242cdc

database:
  enabled: true
  image: postgres:15
  user: admin
  password: devops_password
  db: devops_db
  port: 5432
  storageSize: 1Gi
<<<<<<< HEAD
=======
=======
revision: "0d49183f8dbf71fb1733a95a9684b43e153155d7"
>>>>>>> 52eb8b44b0bbe42e115847b2c5c1efc9a4d46106
>>>>>>> d07cd8f1f649a3cc78d2bbe71238ce955a242cdc
