# Default values for devops-platform.
backend:
  replicaCount: 2
  image:
    repository: khalilsmida/devops-backend
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080

frontend:
  replicaCount: 2
  image:
    repository: khalilsmida/devops-frontend
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: devops-app.local
      paths:
        - path: /api
          pathType: Prefix
          serviceName: backend
        - path: /
          pathType: Prefix
          serviceName: frontend
# Tag for forcing redeployments
<<<<<<< HEAD
revision: "833a5c3614298bac6255ba4f6b88a82e88155d"

database:
  enabled: true
  image: postgres:15
  user: admin
  password: devops_password
  db: devops_db
  port: 5432
  storageSize: 1Gi
=======
revision: "833a5c331617cda496644375ddd5a543a645152a"
>>>>>>> 52eb8b44b0bbe42e115847b2c5c1efc9a4d46106
