{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-platform.fullname" . }}-postgres
spec:
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
  selector:
    app: postgres
{{- end -}}
